project:
  type: website
  output-dir: docs

website:
  description: "The personal homepage of Evgeny D. Cruz"
  site-url: https://evgeny-d-cruz.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Evgeny D. Cruz"
  navbar:
    left:
      - href: blog.qmd
        text: "Blog"
      - href: https://evgeny-d-cruz.github.io/marginalia
        text: "Notes"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



